<a href="https://colab.research.google.com/github/android-kunjapppan/PyTorch-Tutorial/blob/master/Pytorch_Lec1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* Tensor is a Multi Dimensional Array

In [1]:
import torch

x = torch.tensor([5,3])
y = torch.tensor([2,1])

print(x*y)

tensor([10,  3])


In [3]:
x = torch.zeros([2,5])
x, x.shape

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]), torch.Size([2, 5]))

In [6]:
y = torch.rand([2,5]) # Random initialization of [2,5] Tensor
y,y.shape

(tensor([[0.2113, 0.1300, 0.7150, 0.8503, 0.7413],
         [0.4325, 0.6367, 0.6507, 0.5372, 0.2842]]), torch.Size([2, 5]))

In [7]:
# Reshape Function in Torch is view()
y=y.view([1,10])
y,y.shape

(tensor([[0.2113, 0.1300, 0.7150, 0.8503, 0.7413, 0.4325, 0.6367, 0.6507, 0.5372,
          0.2842]]), torch.Size([1, 10]))