<a href="https://colab.research.google.com/github/android-kunjapppan/PyTorch-Tutorial/blob/master/PyTorch_AutoGrad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* To calculate gradients in pytorch
* Automatically creates and stores a function to get the graidents



In [4]:
import torch

x = torch.randn(3,requires_grad=True)
# if requires_grad = False then backward() will give an error
print(x)

y = x+1
print(y) # this will print as grad_fn =<AddBackward0>

z = y*y*2
print(z) # this will print as grad_fn =<MulBackward0>

z=z.mean()
print(z) # this will print as grad_fn =<MeanBackward0>


# TO calculate the gradients
z.backward()  # dz/dx

# grad can be implicitly created only for scalar outputs
# If it is not a scalar, then a vector must be passed as an argument in the backward()

print(x.grad)

tensor([ 0.1112, -0.3664, -0.4563], requires_grad=True)
tensor([1.1112, 0.6336, 0.5437], grad_fn=<AddBackward0>)
tensor([2.4694, 0.8028, 0.5913], grad_fn=<MulBackward0>)
tensor(1.2878, grad_fn=<MeanBackward0>)
tensor([1.4816, 0.8447, 0.7250])


# To prevent from tracking the gradients
1. x.requires_grad_(False)
2. x.detach()
3. with torch.no_grad():


In [5]:
x1 = torch.randn(3,requires_grad=True)
print(x1)

x1.requires_grad_(False)
print(x1)

y = x.detach() # this will create a new tensor with same values but doesnt require gradients
print(y)

with torch.no_grad():
  y1 = x1+2
  print(y)

tensor([ 0.0032, -1.0881, -0.4148], requires_grad=True)
tensor([ 0.0032, -1.0881, -0.4148])
tensor([ 0.1112, -0.3664, -0.4563])
tensor([ 0.1112, -0.3664, -0.4563])


# setting Gradients after each epoch

In [9]:
weights = torch.ones(4,requires_grad = True)

for epoch in range(3):
  model_output = (weights *3).sum()

  model_output.backward()

  print(weights.grad)

  # we must empty the gradients before going into next iteration
  weights.grad.zero_()


tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


# INbuilt optimizer functions

In [10]:
optim = torch.optim.SGD(weights,lr = 0.01)
optim.step()
optim.zero_grad()